spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/ez_pan?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 6sbfevhBMA6o5RPE3gP5
    driver-class-name: org.apache.derby.jdbc.EmbeddedDriver
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
      max-wait: 60000
      time-between-connect-error-millis: 60000
      max-evictable-idle-time-millis: 900000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filter:
        stat:
          enabled: true
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 20MB
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  task:
    scheduling:
      pool:
        size: 3
  mail:
    host: smtp.qq.com
    port: 465
    username: 279298470@qq.com
    password: cggparxpdfcrbgfi
    default-encoding: UTF-8
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      jedis:
        pool:
          max-active: 20
          max-wait: -1
          max-idle: 10
          min-idle: 0
      connect-timeout: 6000

mybatis-plus:
  configuration:
    cache-enabled: true

server:
  port: 8080
  servlet:
    session:
      timeout: PT60M


knife4j:
  enable: true
  setting:
    language: zh_cn
