dbBaseDir: /db/derby

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:derby:${user.dir}/${dbBaseDir}/MyDB;create=true
    username: root
    password: 6sbfevhBMA6o5RPE3gP5
    driver-class-name: org.apache.derby.jdbc.EmbeddedDriver
    continue-on-error: true
    initialization-mode: always
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 20MB
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  task:
    scheduling:
      pool:
        size: 3

mybatis-plus:
  configuration:
    cache-enabled: true

server:
  port: 8080
  servlet:
    session:
      timeout: PT60M


knife4j:
  enable: true
  setting:
    language: zh_cn
